/*
 * This source file was generated by the Gradle 'init' task
 */
package org.assignments;

import org.assignments.A.A;

public class App {

  public static void main(String[] args) {
    new A();
  }

}
